# Generated by Django 5.1.1 on 2024-10-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(default='None', max_length=30),
        ),
    ]
