# Generated by Django 5.1.1 on 2024-10-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
    ]
